### ISSUE TITLE
スクレイピングのサンプルを変えたい

### ISSUE THREAD

**Issue by takanory** [pynyumon/pynyumon#19]
## 目的

* スクレイピングのサンプルの部分、コード更新されてないし github から clone して実行とかそもそもよくわかってなさそう

## 内容案

* サンプルコードへのリンクはバッサリ削除
* requests, bs4 の使い方のサンプルコードをいくつか入れるのはどうだろう

**Comment by kashewnuts** [comment]
@takanory #21 でサンプルが加えられたので、このissueはCloseしてはいかがでしょう？

**Comment by takanory** [comment]
閉じる
