### ISSUE TITLE
事前学習資料の最新化

### ISSUE THREAD

**Issue by a1531yt** [pynyumon/pynyumon#43]
**”「Python言語」はじめの一歩”の Python3.4以降への対応**

- スライドP.72
  3.4以降のPython環境下では (get-pip.pyではなく)、
  　$ python3 -m ensurepip
  とのようにして、pip を有効化してあげればOK。

**Comment by takanory** [comment]
さすがに参照先のスライドまでは更新しないかなーということで却下で
